sudo: required
language: php
php:
- 7.1
env:
  matrix:
  - BUILD_SERVER=1
  - BUILD_CLIENT=1
  - BUILD_WEBDRIVERIO=1 BUILD_SERVER=1
  - CODE_REVIEW=1 REVIEW_STANDARD="Drupal"
  - CODE_REVIEW=1 REVIEW_STANDARD="DrupalPractice"
  - SHELL_REVIEW=1
  global:
  - secure: PZrbjpYSMUZik/+pGvgQ6H4AlO1GB1QVX6WdnMTUePcVCcwTne+ePHtSCjeeJ7f+NELMZ5Rbmh2x9FscvAmDIkM/M5kXygzsRMU8O83mOq3Hw+m1mmXtX10kvE/V+QwFwiFIrSbLJI62gpbQUIdX8vZbSLwJGjvSqjBiPCKgQxFyBQ1HydNzc9qqmQSlICvY5eg7XVPd25RGq8VgKwWwWUyYkAA81vSrQyH6u+VJtuF6462NihO9UFIBbVGahSwCO0enWHvJAjf3GN4hrW5rM6ZAdZwlPgraLIwncqnG1oyQ/wZEVG3vd+ohZNNZIEQtYsUjNuOxuIie3g4p2CCiCqj6FVfZJYccPzSCj1IUBl3V1JdoQgYG94tM+VgMaPaXC8njyUdlRb1qZs1LjP+j1r5vx5f+zIvAIs1Ww6vtTSLyId2jKkqmGqhT/SEi1V9and8IvkN2euLK+l9tgCKQWF5DT8eiUBg2gcSqXDJvmjbN7cp0O8XsWNFPtSpyKQkejeWikpozmoyLeZyNOwgw7tflKlkYwtI7xnTnRB4vi1reM0+rLlrNTBH5M+65C1MBKJ8gR2loUYIXHAdjLu/w2uLXYTn8KQyt0t7+h1RQO485pMNth8F8uljPD6IgD80jFKjW4e4XUAcmDv1FlU7Qf/tZv0HKtAKUqCoEeab/Nxo=
services:
- docker
before_install:
- composer self-update
- export PATH="$HOME/.config/composer/vendor/bin:$PATH"
- sudo pip install docker-compose
install:
- "$TRAVIS_BUILD_DIR/ci-scripts/install_client.sh"
- "$TRAVIS_BUILD_DIR/ci-scripts/install_coder.sh"
- "$TRAVIS_BUILD_DIR/ci-scripts/install_server.sh"
- "$TRAVIS_BUILD_DIR/ci-scripts/install_shell.sh"
before_script:
- "$TRAVIS_BUILD_DIR/ci-scripts/prepare_client.sh"
- sudo service postgresql stop
- sudo service mysql stop
script:
- "$TRAVIS_BUILD_DIR/ci-scripts/test_client.sh"
- "$TRAVIS_BUILD_DIR/ci-scripts/test_coder.sh"
- "$TRAVIS_BUILD_DIR/ci-scripts/test_server.sh"
- "$TRAVIS_BUILD_DIR/ci-scripts/test_shell.sh"
