sudo: required
language: php
php:
- 7.1
env:
  matrix:
  - BUILD_SERVER=1
  - BUILD_CLIENT=1
  - BUILD_WEBDRIVERIO=1 BUILD_SERVER=1
  - CODE_REVIEW=1 REVIEW_STANDARD="Drupal"
  - CODE_REVIEW=1 REVIEW_STANDARD="DrupalPractice"
  - SHELL_REVIEW=1
  global:
  - secure: "KlxO3he7UwTLq3AQVomjvHzmCCUOlRNL/xU1ZHQvQQIs/arKQFrIF/kjvv1AYh28VfNtbk81Uz6+CdbaQlA3kV5XHgVq+5hMCfDbvBnZnJCFSLXVVYG42xk4Rp6hotoQwvquF0Rch6O8FHEMzaO/4CAPqGFVfmtZPecVwGMYoOq5/tJRq4YyxXYmIYPVSiYSUAuaGXpavDn+Dk7YMq0hHUAnGnBKmGY7MtZpPF0+5yAS7GgdvXTJAPDCqg1c98Qw2AyrgAIiTjjzYa8AjQGKPvzvtdsXfe46pVWoVCcnQZbewFtJNMpj5aSnoYzezhTIYTCPhSKmYBLFiPXcIyCd1ni7M6eusbs+0nye16Q9mGxWefYAnmB2Sd/Lt+SauFnKuX2m5KvYDNhL8hEmTqegfo4+zoBIj3l2qKCO4XON/oS8MtkoXZNJYjkVH7HHxMQztXsiBNkcK419NVtf5cyYhlHakSTHeKKg7lvHqU7AjizgiUlUSps0V4lAfRSp7NzHdYWQGMU6vm7qqypm/B/O+iabAIDrCswEo6mpB/0jYZ1m6EGWXC59p361P7pW+tPkYrMFXaVvVIKEMTwQNktRWMFOyVabX9pzz3qg8wRTQ9D52leMEbIOya4272eSCZhfTKWlIYpOt+4XGGzm1kU6KkGEbciBtiTi7y/AByRhMOE="
services:
- docker
before_install:
  openssl aes-256-cbc -K $encrypted_8a88d1e58da1_key -iv $encrypted_8a88d1e58da1_iv -in gdrive-service-account.json.enc -out gdrive-service-account.json -d
- composer self-update
- export PATH="$HOME/.config/composer/vendor/bin:$PATH"
- sudo pip install docker-compose
install:
- "$TRAVIS_BUILD_DIR/ci-scripts/install_client.sh"
- "$TRAVIS_BUILD_DIR/ci-scripts/install_coder.sh"
- "$TRAVIS_BUILD_DIR/ci-scripts/install_server.sh"
- "$TRAVIS_BUILD_DIR/ci-scripts/install_shell.sh"
before_script:
- "$TRAVIS_BUILD_DIR/ci-scripts/prepare_client.sh"
- sudo service postgresql stop
- sudo service mysql stop
script:
- "$TRAVIS_BUILD_DIR/ci-scripts/test_client.sh"
- "$TRAVIS_BUILD_DIR/ci-scripts/test_coder.sh"
- "$TRAVIS_BUILD_DIR/ci-scripts/test_server.sh"
- "$TRAVIS_BUILD_DIR/ci-scripts/test_shell.sh"
