sudo: required
language: php
php:
- 7.1
env:
  matrix:
  - BUILD_SERVER=1
  - BUILD_CLIENT=1
  - BUILD_WEBDRIVERIO=1 BUILD_SERVER=1
  - CODE_REVIEW=1 REVIEW_STANDARD="Drupal"
  - CODE_REVIEW=1 REVIEW_STANDARD="DrupalPractice"
  - SHELL_REVIEW=1
  global:
  - secure: bcFCKst1V0Y8SI6Yr2Irv2wC4FnVwF6J2nH4bHMMmR8gCplLUhZ831sFGe/m5V15r3wR/kFCdBU3sMTu8GhwMSONzuQyXN3Fv7c3Qc+megaZIAmiV8xjeguUKZOW/6kE2SDI3CCe3xS7KisLuUwQvQNL3yesSdUmG6QueZQ4IT0Cj2LMhnJVJos7xJ46aqc6qCvt23Sx8q2qGskAYPdzDCybbR9BozVR4jIeUOgYUFzvAad6zGprymqmi3+PgV2mnu50Ib3Z1hZidgqKN/IJKK2Amn6/YAlfDz95o4hOSx3U4hA0pV1FrDrBjMKY9Ue+E4BkFMhq7q5XZpL8/V/VVxeO5JRfOq7/6IhaIw0CSeKjnnJ9dmWRMYP0DkmjNJpaM4xsk6w2EGs6lfUEbdRuA3N/lxgVp3wtUD6A3ey52Ip+yLvXidbX4op7QMlkBrNehyw5+1Hi087KjKdEk6uDlnys7Mygf4g5lJO0XZQ9i397Et5CpxDarvgGoJqE7ZY9E7XDxXEoXKakYP98pgLFgP2otC/53Emtxf1libUbxQsWzNvhWLK7QY8GgPooMfaN9a5ct0dpi6LgcAo7e44z9VDLTBGgddGlapcKlXT0XtKZP/nJGyqfZg8pwF8ConcsAAxa43sBrl5xunQ/8OSqAZscNF1KFv9vXfa4UpMGHvU=
services:
- docker
before_install:
- composer self-update
- export PATH="$HOME/.config/composer/vendor/bin:$PATH"
- sudo pip install docker-compose
- openssl aes-256-cbc -K $encrypted_8a88d1e58da1_key -iv $encrypted_8a88d1e58da1_iv
  -in gdrive-service-account.json.enc -out gdrive-service-account.json -d
install:
- "$TRAVIS_BUILD_DIR/ci-scripts/install_client.sh"
- "$TRAVIS_BUILD_DIR/ci-scripts/install_coder.sh"
- "$TRAVIS_BUILD_DIR/ci-scripts/install_server.sh"
- "$TRAVIS_BUILD_DIR/ci-scripts/install_shell.sh"
before_script:
- "$TRAVIS_BUILD_DIR/ci-scripts/prepare_client.sh"
- sudo service postgresql stop
- sudo service mysql stop
script:
- "$TRAVIS_BUILD_DIR/ci-scripts/test_client.sh"
- "$TRAVIS_BUILD_DIR/ci-scripts/test_coder.sh"
- "$TRAVIS_BUILD_DIR/ci-scripts/test_server.sh"
- "$TRAVIS_BUILD_DIR/ci-scripts/test_shell.sh"
