sudo: require

language: php
php:
  - 5.6

env:
  - BUILD_SERVER=1
  - CODE_REVIEW=1
    REVIEW_STANDARD="Drupal"
  - CODE_REVIEW=1
    REVIEW_STANDARD="DrupalPractice"

services:
  - docker

cache:
  directories:
    - sysconfcpus

before_install:
  - composer self-update
  - export PATH="$HOME/.config/composer/vendor/bin:$PATH"

install:
  - $TRAVIS_BUILD_DIR/ci-scripts/install_coder.sh
  - $TRAVIS_BUILD_DIR/ci-scripts/install_server.sh

script:
  - $TRAVIS_BUILD_DIR/ci-scripts/test_coder.sh
  - $TRAVIS_BUILD_DIR/ci-scripts/test_server.sh
