sudo: required
language: php
php:
- 7.1
env:
  matrix:
  - BUILD_SERVER=1
  - BUILD_CLIENT=1
  - BUILD_WEBDRIVERIO=1 BUILD_SERVER=1
  - CODE_REVIEW=1 REVIEW_STANDARD="Drupal"
  - CODE_REVIEW=1 REVIEW_STANDARD="DrupalPractice"
  - SHELL_REVIEW=1
  global:
  - secure: nEpO8zOkc6UzDxd/HkilS37KquXmExu4MXtIiNHkTDF93zIZvLnQxSG67dNRZqRzwTD3hBq61JEOiOpHdlu4tZoc4ghr34Z2f+3YVAvVPra4cHtzwHNqP+nYrYhRdEuWye428SjFws4GhzExY60Si6RFRwnVtFZFl8ZhWI0hBPpsWAzQu4p7JxbvP0L0RTrj0u6zuvDxw686551cUcFAGWVG84y41UoGSmpeucgtcm962/lxGeWVYj4IIle4DDTjmzNkogoLFmUXMj3YasaLGFznfgscTSecVYPSkDAXatngYfqE5sflt9E2g1f+5vmjRGUdL5vDCE2sB3yor6JSi5PhtM7xpH4HSNzMSWLSoex+K8yfP61aAOy1cVyCxVhBzBnEnLMPPd3xQnRRGCMIaFfRcg+qhJg/FphFQrcPZ0rXw/OjH6x6qMrRh90K8cRETCrng8/P3hOnOYjJVodNt1QvvnMNlcYDGnd4zZblnY0ChgOq/wBYnkqoR0hjDXsyegwR1SiTqH0BqC9k5RI+AI/jKoaOcX8ImihjhLG0BqrEnTuo7B5FSLIUBmtiFx4JLbP00gHNnkNmvsAzM4eUh23zBR1QEUpziixIVGqdOz6ou/IPBrQ+19G62ZKn1SSjSBa9REwZ4gUzP/CaNNtGZDdHJA6KrnZdAyL3dc6vkcQ=
services:
- docker
before_install:
- composer self-update
- export PATH="$HOME/.config/composer/vendor/bin:$PATH"
- sudo pip install docker-compose
- openssl aes-256-cbc -K $encrypted_9f8daefef5b9_key -iv $encrypted_9f8daefef5b9_iv
  -in gdrive-service-account.json.enc -out gdrive-service-account.json -d
install:
- "$TRAVIS_BUILD_DIR/ci-scripts/install_client.sh"
- "$TRAVIS_BUILD_DIR/ci-scripts/install_coder.sh"
- "$TRAVIS_BUILD_DIR/ci-scripts/install_server.sh"
- "$TRAVIS_BUILD_DIR/ci-scripts/install_shell.sh"
before_script:
- "$TRAVIS_BUILD_DIR/ci-scripts/prepare_client.sh"
- sudo service postgresql stop
- sudo service mysql stop
script:
- "$TRAVIS_BUILD_DIR/ci-scripts/test_client.sh"
- "$TRAVIS_BUILD_DIR/ci-scripts/test_coder.sh"
- "$TRAVIS_BUILD_DIR/ci-scripts/test_server.sh"
- "$TRAVIS_BUILD_DIR/ci-scripts/test_shell.sh"
