<?php

/**
 * @file
 * Code for the Hedley Event feature.
 */

include_once 'hedley_event.features.inc';

/**
 * Return events by group.
 *
 * @param object $group
 *   The group.
 * @param string $language_code
 *   The language code (e.g. "he", "ar").
 * @param bool $show_as_block
 *   (optional) Determine if content will be shown as a block, defaults to
 *   FALSE.
 * @param bool $promoted_only
 *   (optional) Determine if content should be promoted only, defaults to FALSE.
 * @param int $topic_tid
 *   (optional) The topic ID, defaults to 0.
 *
 * @return array
 *   Array with the events list.
 */
function hedley_event_get_events_by_group($group, $language_code, $show_as_block = FALSE, $promoted_only = FALSE, $topic_tid = 0) {
  // Determine the events setting depending on the block configuration.
  $range = $show_as_block ? 5 : 100;

  // Get contact nodes by group.
  $nodes = hedley_municipality_get_nodes_by_current_user_type('event', $range, $group, $promoted_only, $topic_tid);
  if (!$nodes) {
    // No contacts found.
    return NULL;
  }

  $events = [];
  foreach ($nodes as $node) {
    if (!$event = hedley_event_get_event_item($node, $language_code, 'square_large_image')) {
      continue;
    }
    $events[] = $event;
  }

  // Sort events by date ASC.
  usort($events, 'hedley_event_sort_by_date');

  // Put the recurring events first.
  usort($events, 'hedley_event_sort_recurring_first');

  return $events;
}

/**
 * Get the elm element for an Event.
 *
 * @param object $event
 *   The event.
 * @param string $language_code
 *   The language code (e.g. "he", "ar").
 * @param string $image_style
 *   The image style for the event image, defaults to large.
 *
 * @return array|bool
 *   The event item or nothing if something is missing.
 */
function hedley_event_get_event_item($event, $language_code, $image_style = 'large') {
  global $user;

  $wrapper = entity_metadata_wrapper('node', $event);
  $wrapper->language($language_code);

  // Ignore events without a title in the current language.
  if (!$wrapper->label()) {
    return FALSE;
  }

  $image = $wrapper->field_image->value();
  $date = $wrapper->field_date->value();

  if (empty($date)) {
    // Date is required but just in case date is missing in some translation.
    return FALSE;
  }

  $location_unfiltered = $wrapper->field_location->value();
  // Keep only "url" and "title" sub properties and remove any value that is
  // missing one of those properties, although they are required but just in
  // case.
  $location = array_filter(['url' => $location_unfiltered['url'], 'title' => $location_unfiltered['title']], function ($value) {
    return !is_null($value);
  });

  // Remove empty values (elm expects the correct value or nothing), but keep
  // the values with `FALSE` value.
  $event = array_filter([
    'id' => $wrapper->getIdentifier(),
    'name' => check_plain($wrapper->label()),
    'image_url' => !empty($image) ? image_style_url($image_style, $image['uri']) : hedley_municipality_get_default_image($wrapper->getBundle()),
    'description' => !empty($wrapper->body->value()) ? $wrapper->body->value->value() : NULL,
    'date' => hedley_event_timestamp_to_iso8601($date['value']),
    // Make sure the end date isn't the same as the start date.
    'end_date' => !empty($date) && $date['value2'] && $date['value'] != $date['value2'] ? hedley_event_timestamp_to_iso8601($date['value2']) : NULL,
    'recurring_weekly' => $wrapper->field_recurring_weekly->value(),
    'ticket_price' => (int) $wrapper->field_ticket_price->value() ? $wrapper->field_ticket_price->value() : NULL,
    'location' => !empty($location) ? $location : NULL,
    'showEditLink' => og_node_access($event, 'update', $user) == NODE_ACCESS_ALLOW,
  ], function ($value) {
    return !is_null($value);
  });

  return $event;
}

/**
 * Convert Unix timestamp to ISO8601.
 *
 * @param int $timestamp
 *   The Unix timestamp.
 *
 * @return false|string
 *   The converted timestamp.
 */
function hedley_event_timestamp_to_iso8601($timestamp) {
  return date('c', $timestamp);
}

/**
 * Helper function; Sort events by date.
 */
function hedley_event_sort_by_date($a, $b) {
  if ($a['date'] == $b['date']) {
    return 0;
  }
  return ($a['date'] < $b['date']) ? -1 : 1;
}

/**
 * Helper function; Sort events by recurring first.
 */
function hedley_event_sort_recurring_first($a, $b) {
  if ($a['recurring_weekly'] == $b['recurring_weekly']) {
    return 0;
  }
  return ($a['recurring_weekly'] > $b['recurring_weekly']) ? -1 : 1;
}
