<?php

/**
 * @file
 * Code for the Hedley Municipality feature.
 */

include_once 'hedley_municipality.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function hedley_municipality_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Get nodes of a municipality group, according to current profile type.
 *
 * @param string $bundle
 *   The wanted nodes bundle.
 * @param int $max_range
 *   Maximal amount of nodes to fetch.
 * @param int $municipality_node
 *   Optional municipality node to filter by.
 * @param bool $promoted_only
 *   Whether to get only promoted nodes.
 * @param int $topic_tid
 *   Optional filter by field_topics.
 *
 * @return array Node objects.
 *   Node objects.
 */
function hedley_municipality_get_nodes($bundle, $max_range, $municipality_node = NULL, $promoted_only = FALSE, $topic_tid = 0) {
  // Get promoted FAQ nodes of the viewed municipality.
  $query = new EntityFieldQuery();
  $query
    ->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', $bundle)
    ->propertyCondition('status', NODE_PUBLISHED)
    ->propertyOrderBy('created', 'DESC')
    // Filter by current profile type.
    ->fieldCondition('field_profile_types', 'tid', hedley_terms_get_current_profile_type_tid())
    ->range(0, $max_range);

  // Filter by municipality.
  if ($municipality_node) {
    $query->fieldCondition(OG_AUDIENCE_FIELD, 'target_id', $municipality_node->nid);
  }
  // Filter by promoted nodes.
  if ($promoted_only) {
    $query->propertyCondition('promote', NODE_PROMOTED);
  }
  // Filter by current topic.
  if ($topic_tid) {
    $query->fieldCondition('field_topics', 'tid', $topic_tid);
  }
  $result = $query->execute();

  return !empty($result['node']) ? node_load_multiple(array_keys($result['node'])) : [];
}

/**
 * Implements hook_entity_info_alter().
 *
 * Adding teaser view mode for the municipality homepage.
 */
function hedley_municipality_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['homepage_teaser'] = [
    'label' => t('Municipality homepage teaser'),
    'custom settings' => TRUE,
  ];
}

/**
 * Get the current municipality context.
 *
 * @return mixed
 *   The municipality node, when available.
 */
function hedley_municipality_get_current() {
  $purl_gids = og_purl_og_context_handler();
  if (empty($purl_gids['node']) || count($purl_gids['node']) != 1) {
    return FALSE;
  }
  return node_load(reset($purl_gids['node']));
}
