<?php

/**
 * @file
 * Populate Hedley content.
 */

/**
 * Implements hook_migrate_api().
 */
function hedley_migrate_migrate_api() {
  $migrations = [
    // Nodes.
    'HedleyMigrateActions',
    'HedleyMigrateFaqs',
    'HedleyMigrateItems',
    'HedleyMigrateMunicipalities',
    'HedleyMigrateNews',
    // Terms.
    'HedleyMigrateProfileTypes',
    'HedleyMigrateTopics',
    // Users.
    'HedleyMigrateUsers',
  ];

  $api['api'] = 2;
  foreach ($migrations as $migration) {
    $api['migrations'][$migration] = ['class_name' => $migration];
  }

  return $api;
}
