<?php

/**
 * @file
 * Code for the Hedley Elm feature.
 */

include_once 'hedley_elm.features.inc';

// Define constants for elm page types.
define('HEDLEY_ELM_CONTACTS', 'contacts');
define('HEDLEY_ELM_EVENT', 'event');
define('HEDLEY_ELM_EVENTS', 'events');

/**
 * Implements hook_ctools_plugin_directory().
 */
function hedley_elm_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools') {
    return 'plugins/' . $plugin;
  }
}
