<?php

/**
 * @file
 * Code for the Hedley Action feature.
 */

include_once 'hedley_action.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function hedley_action_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_node_presave().
 *
 * Fix empty entity references on the action's field_action_sections. For some
 * reason when the hardcopy reference is left empty, it's being saved as an
 * empty string, which is not allowed on the multifield table. So we convert
 * empty strings to NULLs for this column.
 */
function hedley_action_node_presave($node) {
  if ($node->type != 'action') {
    return;
  }

  if (empty($node->field_action_sections)) {
    return;
  }

  // Iterate all action sections values, and search for hardcopy_form references
  // that are set to an empty string.
  foreach ($node->field_action_sections as &$language_values) {
    foreach ($language_values as &$value) {
      if (!isset($value['field_section_hardcopy_form'][LANGUAGE_NONE][0]['target_id'])) {
        continue;
      }
      if ($value['field_section_hardcopy_form'][LANGUAGE_NONE][0]['target_id'] === '') {
        // Convert the reference to NULL.
        $value['field_section_hardcopy_form'][LANGUAGE_NONE][0]['target_id'] = NULL;
      }
    }
  }
}

/**
 * Get the title of the action wrapped in a link.
 *
 * The link's logic is as follows:
 * 1. The field link is NOT empty, return the link inside this field.
 * 2. The field link is empty, return the link to the entity itself.
 *
 * @param object $wrapper
 *   The action entity wrapper.
 * @param array $class
 *   The CSS classes to add to the link, defaults to empty.
 *
 * @return string
 *   The action's label wrapped in a link.
 */
function hedley_action_get_action_title_link($wrapper, array $class = []) {
  // Default link of the action.
  $href = url('node/' . $wrapper->getIdentifier(), ['absolute' => TRUE]);
  $target = '';
  // Change the link to the one specified in the link field if there's one.
  if ($link = $wrapper->field_link->value()) {
    // Open external links in a new tab.
    $target = url_is_external($link['url']) ? '_blank' : '';
    $href = url($link['url']);
  }

  return l($wrapper->label(), $href, [
    'attributes' => [
      'target' => $target,
      'class' => $class,
    ],
  ]);
}
