<?php
/**
 * @file
 * hedley_action.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function hedley_action_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'og_vocabulary'.
  $field_bases['og_vocabulary'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'og_vocabulary',
    'indexes' => array(
      'target_id' => array(
        0 => 'target_id',
      ),
    ),
    'locked' => 0,
    'module' => 'entityreference',
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'handler' => 'base',
      'handler_settings' => array(
        'behaviors' => array(
          'og_vocab' => array(
            'status' => TRUE,
          ),
          'taxonomy-index' => array(
            'status' => TRUE,
          ),
        ),
        'target_bundles' => array(),
      ),
      'target_type' => 'taxonomy_term',
    ),
    'translatable' => 0,
    'type' => 'entityreference',
  );

  return $field_bases;
}
