<?php

/**
 * @file
 * Code for the Hedley Action feature.
 */

include_once 'hedley_action.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function hedley_action_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_node_presave().
 *
 * Fix empty entity references on the action's field_action_sections. For some
 * reason when the hardcopy reference is left empty, it's being saved as an
 * empty string, which is not allowed on the multifield table. So we convert
 * empty strings to NULLs for this column.
 */
function hedley_action_node_presave($node) {
  if ($node->type != 'action') {
    return;
  }

  if (empty($node->field_action_sections)) {
    return;
  }

  // Iterate all action sections values, and search for hardcopy_form references
  // that are set to an empty string.
  foreach ($node->field_action_sections as &$language_values) {
    foreach ($language_values as &$value) {
      if (!isset($value['field_section_hardcopy_form'][LANGUAGE_NONE][0]['target_id'])) {
        continue;
      }
      if ($value['field_section_hardcopy_form'][LANGUAGE_NONE][0]['target_id'] === '') {
        // Convert the reference to NULL.
        $value['field_section_hardcopy_form'][LANGUAGE_NONE][0]['target_id'] = NULL;
      }
    }
  }
}

/**
 * Implements hook_node_validate().
 *
 * Validate that one the fields "Link" or "Action section" have some kind of a
 * value.
 */
function hedley_action_node_validate($node, $form, &$form_state) {
  if ($node->type != 'action') {
    return;
  }

  // Get fields values.
  $field_link_values = $form_state['values']['field_link'];
  $field_action_sections_values = $form_state['values']['field_action_sections'];

  // Fields are empty by default.
  $one_field_is_filled = FALSE;
  foreach ($field_link_values as $field_link_value) {
    // Check values in all languages.
    $first_value = $field_link_value[0];
    if ($first_value['title'] && $first_value['url']) {
      $one_field_is_filled = TRUE;
    }
  }

  foreach ($field_action_sections_values as $field_action_sections_value) {
    // Check values in all languages.
    $first_value = $field_action_sections_value[0];
    if ($first_value['field_section_title'][LANGUAGE_NONE][0]['value']) {
      $one_field_is_filled = TRUE;
    }
  }

  if (!$one_field_is_filled) {
    // Neither fields are filled, display a form error.
    form_set_error('action_valid_data', t('At least one of the fields "Link" or "Action section" should have a valid value.'));
  }

}

/**
 * Get the title of the action wrapped in a link.
 *
 * The link's logic is as follows:
 * 1. The field link is NOT empty, return the link inside this field.
 * 2. The field link is empty, return the link to the entity itself.
 *
 * @param object $wrapper
 *   The action entity wrapper.
 * @param array $class
 *   The CSS classes to add to the link, defaults to empty.
 *
 * @return string
 *   The action's label wrapped in a link.
 */
function hedley_action_get_action_title_link($wrapper, array $class = []) {
  // Default link of the action.
  $href = url('node/' . $wrapper->getIdentifier(), ['absolute' => TRUE]);
  $target = '';
  // Change the link to the one specified in the link field if there's one.
  if ($link = $wrapper->field_link->value()) {
    // Open external links in a new tab.
    $target = url_is_external($link['url']) ? '_blank' : '';
    $href = url($link['url']);
  }

  return l($wrapper->label(), $href, [
    'attributes' => [
      'target' => $target,
      'class' => $class,
    ],
  ]);
}

/**
 * A helper function to keep the icons classes of the 'action section icon'.
 *
 * @param string $key
 *   The key of the icon.
 *
 * @return mixed|null
 *   The 'Font Awesome' class of the provided key.
 */
function hedley_action_get_section_icon_class($key) {
  $classes = [
    'add_to_calendar' => 'calendar',
    'alarm' => 'bell',
    'check' => 'check-square-o',
    'find' => 'search',
    'handshake' => 'handshake-o',
    'mail' => 'envelope-o',
    'phone' => 'mobile',
  ];

  return isset($classes[$key]) ? $classes[$key] : NULL;
}
