<?php

/**
 * @file
 * Code for the Hedley contact feature.
 */

include_once 'hedley_contact.features.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Remove the title from the contact node form.
 */
function hedley_contact_form_contact_node_form_alter(&$form, &$form_state) {
  $form['title']['#access'] = FALSE;
}

/**
 * Implements hook_node_presave().
 *
 * Set contact node title according to the municipality's default language.
 */
function hedley_contact_node_presave($node) {
  if ($node->type != 'contact') {
    return;
  }

  $municipality_wrapper = entity_metadata_wrapper('node', hedley_municipality_node_municipality($node));
  if ($language_code = hedley_municipality_get_non_empty_language_for_field($node->field_last_name, $municipality_wrapper->field_default_language->value())) {
    $node->title = trim($node->field_first_name[$language_code][0]['value'] . ' ' . $node->field_last_name[$language_code][0]['value']);
  }
}

/**
 * Format the contact reception hours array, grouped by hours and days.
 *
 * @param object $node
 *   A contact node.
 *
 * @return array
 *   The formatted hours, keyed by days labels.
 */
function hedley_contact_get_reception_hours($node) {
  if (empty($node->field_reception_hours[LANGUAGE_NONE])) {
    return [];
  }

  // Fetch values from reception hours multifield. Accessing the node directly
  // because the wrapper doesn't seem to work consistently with multifields.
  $reception_hours = [];
  foreach ($node->field_reception_hours[LANGUAGE_NONE] as $reception_hour) {
    if (!isset($reception_hour['field_hours'][LANGUAGE_NONE][0]['value']) || !isset($reception_hour['field_weekday'][LANGUAGE_NONE][0]['value'])) {
      continue;
    }

    // The weekday as int from Sunday = 0 to Saturday = 6.
    $day_index = intval($reception_hour['field_weekday'][LANGUAGE_NONE][0]['value']);
    $hours = check_plain($reception_hour['field_hours'][LANGUAGE_NONE][0]['value']);
    // Group the reception hours by day, as a unified string.
    if (!isset($reception_hours[$day_index])) {
      $reception_hours[$day_index] = $hours;
    }
    else {
      $reception_hours[$day_index] .= ', ' . $hours;
    }
  }
  // Sort by day.
  ksort($reception_hours);

  // Group days with identical hours together.
  $reception_hours_grouped = [];
  foreach ($reception_hours as $day_index => $hours) {
    if (!isset($reception_hours_grouped[$hours])) {
      $reception_hours_grouped[$hours] = $day_index;
    }
    else {
      $reception_hours_grouped[$hours] .= '|' . $day_index;
    }
  }

  // Format the hours.
  $formatted_hours = [];
  // Day names, for converting the day indices to names.
  $day_names = [
    t('Sunday'),
    t('Monday'),
    t('Tuesday'),
    t('Wednesday'),
    t('Thursday'),
    t('Friday'),
    t('Saturday'),
  ];
  foreach ($reception_hours_grouped as $hours => $days) {
    $days = explode('|', $days);
    $days_text = '';
    foreach ($days as $delta => $day_index) {
      // In case the current day is is between two consecutive days, then add a
      // dash instead of listing it. E.g. "Monday - Thursday".
      if (isset($days[$delta - 1]) && $days[$delta - 1] == $day_index - 1 && isset($days[$delta + 1]) && $days[$delta + 1] == $day_index + 1) {
        // Remove the previous dash if any, and re-add the dash.
        $days_text = rtrim($days_text, ', - ');
        $days_text .= ' - ';
      }
      else {
        $days_text .= $day_names[$day_index] . ', ';
      }
    }
    // Remove the trailing comma.
    $days_text = rtrim($days_text, ', ');
    $formatted_hours[] = [
      'days' => $days_text,
      'hours' => $hours,
    ];
  }

  return $formatted_hours;
}

/**
 * Return contacts by group.
 *
 * @param object $group
 *   The group.
 * @param string $language_code
 *   The language code (e.g. "he", "ar").
 *
 * @return array
 *   Array with the contacts list.
 */
function hedley_contact_get_contacts_by_group($group, $language_code) {
  // Get contact nodes by group.
  $nodes = hedley_municipality_get_nodes('contact', 100, $group, FALSE, 0, 'ASC');
  if (!$nodes) {
    // No contacts found.
    return NULL;
  }
  $contacts = [];
  foreach ($nodes as $node) {
    $wrapper = entity_metadata_wrapper('node', $node);
    $wrapper->language($language_code);

    // Ignore contacts without a name and a department in the current language.
    if (!$wrapper->field_last_name->value() && !$wrapper->field_department->value()) {
      continue;
    }

    $image = $wrapper->field_image->value();

    $name = check_plain($wrapper->field_first_name->value()) . ' ' . check_plain($wrapper->field_last_name->value());
    if (!trim($name) && $wrapper->field_department->value()) {
      // If we have only the field department filled it means the contact card
      // is a general department card, not a specific worker.
      $name = $wrapper->field_department->label();
    }

    // Get the topics related to the user, if not empty.
    $topics_array = array();
    $topics = $wrapper->field_topics->value();
    if (!empty($wrapper->field_topics->raw())) {
      foreach ($topics as $topic) {
        $topic_wrapper = entity_metadata_wrapper('taxonomy_term', $topic);
        $topics_array[] = [
          'id' => $topic_wrapper->getIdentifier(),
          'name' => $topic_wrapper->label(),
          'color' => $topic_wrapper->field_color->value(),
        ];
      }
    }

    $contact = [
      'id' => $wrapper->getIdentifier(),
      'name' => $name,
      'image_url' => $image ? image_style_url('medium', $image['uri']) : '',
      'phone' => check_plain($wrapper->field_phone->value()),
      'fax' => check_plain($wrapper->field_fax->value()),
      'email' => check_plain($wrapper->field_email->value()),
      'address' => check_plain($wrapper->field_address->value()),
      'job_title' => check_plain($wrapper->field_job_title->value()),
      'topics' => $topics_array,
      'reception_hours' => hedley_contact_get_reception_hours($node),
    ];

    // Remove empty values (elm expects the correct value or nothing).
    $contacts[] = array_filter($contact);
  }

  return $contacts;

}
